version: "3"
services:
  web:
    build: ./Docker
    volumes:
      - ./node_modules:/var/www/node_modules
      - ./vendor:/var/www/vendor
      - ./data:/var/www/data
      - ./dist:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:80"