version: "3"
services:
  web:
    build: ./docker
    command: sh -c "httpd && echo Sever listening on localhost\:8000/~fairyski && tail -f /var/www/logs/access.log"
    volumes:
      - ./:/home/fairyski/
    working_dir: /home/fairyski
    ports:
      - "8000:80"
  node:
    image: node:10.15-alpine
    command: sh -c "yarn watch"
    volumes:
      - ./:/app
    working_dir: /app

