version: 2.1
executors:
  nodejs:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/project
  php:
    docker:
      - image: circleci/php:7.2
    working_directory: ~/project
jobs:
  lint_check:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install Yarn Packages
          command: yarn
          working_directory: ~/project/frontend
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~project/frontend/node_modules
      - run:
          name: Run ESLint
          command: yarn lint
          working_directory: ~/project/frontend
      - persist_to_workspace:
          root: .
          paths:
            - .
  type_check:
    executor: nodejs
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check types using tsc
          command: cd ~/project/frontend && yarn type-check
          working_directory: ~/project/frontend
  php_build:
    executor: php
    steps:
      - attach_workspace:
          at: .
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: nodejs
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn build
      - run:
          name: install lftp
          command: sudo apt install -y lftp
      - run:
          name: add host key to known_hosts
          command: mkdir ~/.ssh; echo www.stb.tsukuba.ac.jp,130.158.69.105 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKl0n5HLyPwY8yCKujl8K1zKnMRLA7rQMtcbsOIn/Sv/uKjkUfSlLOMeXb7OwIjQQotFSps1dP2K27hOaDdPUSM= > ~/.ssh/known_hosts
      - run:
          name: copy public directory to stb server
          command: lftp -u $STB_USER,$STB_PASSWORD -e "mirror -Rev public/. public_html/.; bye" sftp://www.stb.tsukuba.ac.jp
      - run:
          name: copy vendor directory to stb server
          command: lftp -u $STB_USER,$STB_PASSWORD -e "mirror -Rev vendor/. vendor/.; bye" sftp://www.stb.tsukuba.ac.jp
workflows:
  main_workflow:
    jobs:
      - lint_check
      - type_check:
          requires:
            - lint_check
      - php_build:
          requires:
            - type_check
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - php_build
          filters:
            branches:
              only: master
